<a href="https://colab.research.google.com/github/TusharVaibhavK/ProjectMSR/blob/dev2/Yoshi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [ ]:
Dataset = pd.read_csv('Data.csv')
X = Dataset.iloc[:, :-1]
Y = Dataset.iloc[:, -1]
france = Dataset.iloc[0]
print(Dataset)


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
print(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [ ]:
print(Y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [ ]:
print(france)

Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object


In [ ]:
from sklearn.impute import SimpleImputer as si
imputer = si(missing_values=np.NaN, strategy = 'mean')

Dataset.Age = imputer.fit_transform(Dataset['Age'].values.reshape(-1,1))[:,0]
Dataset.Salary = imputer.fit_transform(Dataset['Salary'].values.reshape(-1,1))[:,0]

Dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

NameError: ignored

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[0.0e+00 0.0e+00 1.0e+00     nan 5.2e+04]
 [0.0e+00 1.0e+00 0.0e+00 4.0e+01     nan]
 [1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]]
[[0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]
[0 1 0 0 1 1 0 1]
[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
X_test[:, 3:] = sc.fit_transform(x_test[:, 3:])
print(X_train)
print(X_test)

[[ 0.          0.          1.                 nan -1.018224  ]
 [ 0.          1.          0.         -0.03891021         nan]
 [ 1.          0.          0.          0.50583275  0.58347667]
 [ 0.          0.          1.         -0.31128169 -0.2974587 ]
 [ 0.          0.          1.         -1.80932482 -1.33856413]
 [ 1.          0.          0.          1.0505757   1.1440719 ]
 [ 0.          1.          0.          1.32294718  1.46441204]
 [ 1.          0.          0.         -0.71983891 -0.5377138 ]]
[[ 0.  1.  0. -1. -1.]
 [ 1.  0.  0.  1.  1.]]
